
# experiment duration time must be in seconds
START_TIME = 0
END_TIME = 20
EXPERIMENT_DURATION = 1200

# timewindow size in seconds for snapshot creation
TIME_WINDOW = 60

# arena diameter in mm
ARENA_DIAMETER = 61

#video FPS
FPS = 24

TREATMENTS = ["Cs_5DIZ"]

#"Cs_5DIZ", "LDA_5DIZ", "OCT_5DIZ"] 
# TREATMENTS = ["CsCh"]

N_OF_SAMPLES = 12
N_RANDOM_GROUPS = 10000
