START_TIME = 0
END_TIME = 30

# experiment duration time must be in seconds
EXPERIMENT_DURATION = 1800

# timewindow size in seconds for snapshot creation
TIME_WINDOW = 60

# arena diameter in mm
ARENA_DIAMETER = 61

#video FPS
FPS = 24

TREATMENTS = ['CsCh', 'ELAV', 'ELAVxSMBA', 'SMBA', 'TMBC', 'TMBCxELAV', 'w1118'] 

N_OF_SAMPLES = 12
N_RANDOM_GROUPS = 10000
