START_TIME = 0
END_TIME = 20

# experiment duration time must be in seconds
EXPERIMENT_DURATION = 1200

# timewindow size in seconds for snapshot creation
TIME_WINDOW = 60

# arena diameter in mm
ARENA_DIAMETER = 61

#video FPS
FPS = 24

# TREATMENTS = ["pseudo_Cs_5DIZ", "pseudo_LDA_5DIZ"]
TREATMENTS = ["Cs_5DIZ", "LDA_5DIZ", "pseudo_Cs_5DIZ", "pseudo_LDA_5DIZ"]

N_OF_SAMPLES = 12
N_RANDOM_GROUPS = 10000
