# start and end time must be in minutes
START_TIME = 0
END_TIME = 20

# experiment duration time must be in seconds
EXPERIMENT_DURATION = 1200

# timewindow size in seconds for snapshot creation
TIME_WINDOW = 60

# arena diameter in mm
ARENA_DIAMETER = 61 

#video FPS
FPS = 24

# list of strings of treatment names, etc. ["CS", "CS_LDA", "LDA"]
TREATMENTS = [] 

# number of pseudo random groups
N_RANDOM_GROUPS = 10000
# number of samples for pseudo random group
N_OF_SAMPLES = 12
