
START_TIME = 3
END_TIME = 23
# experiment duration time must be in seconds
EXPERIMENT_DURATION = 1200

# timewindow size in seconds for snapshot creation
TIME_WINDOW = 30

# arena diameter in mm
ARENA_DIAMETER = 60
#video FPS
FPS = 24

# TREATMENTS = [""] #
# TREATMENTS = ["OCT_5DIZ"]
TREATMENTS = ["CsCh", "CTRL_5DIZ", "OCT_5DIZ", "LDA_5DIZ", "pseudo_CsCh"]

N_RANDOM_GROUPS = 2000
